// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class Address
    {
        public int PartyKey { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string CountryA3 { get; set; }
        public string Country { get; set; }
        public string AddressTypeCd { get; set; }
        public string AddressTypeDesc { get; set; }
        public string SourceSystem { get; set; }
    }
}