// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class Broker
    {
        public int PartyKey { get; set; }
        public string BrokerId { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string DistributionChannelCd { get; set; }
        public string DistributionChannelDesc { get; set; }
        public string IdentificationNbr { get; set; }
        public string ActiveFlag { get; set; }
        public string SourceSystem { get; set; }
    }
}