// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class Contact
    {
        public int PartyKey { get; set; }
        public string ContactValue { get; set; }
        public string ContactTypeCd { get; set; }
        public string ContactTypeDesc { get; set; }
        public string SourceSystem { get; set; }
    }
}