// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class Organization
    {
        public int PartyKey { get; set; }
        public DateOnly? FoundationDate { get; set; }
        public string OrganizationKindCd { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string TaxIdentificationNumber { get; set; }
        public string IdentificationNumber { get; set; }
        public string MarketingConsent { get; set; }
        public string SourceSystem { get; set; }
    }
}