// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class PartyAgreementBase
    {
        public int PartyKey { get; set; }
        public int? AgreementBaseKey { get; set; }
        public string PartyAgreementBaseRoleCd { get; set; }
        public string PartyAgreementBaseRoleDesc { get; set; }
        public string SourceSystem { get; set; }
    }
}