// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class PensionAgreement
    {
        public int AgreementBaseKey { get; set; }
        public string PensionPlanCd { get; set; }
        public string PensionPlanDesc { get; set; }
    }
}