// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTools.Models
{
    public partial class Person
    {
        public int PartyKey { get; set; }
        public DateOnly? BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string GenderCd { get; set; }
        public string GenderDesc { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public string PrefixTitles { get; set; }
        public string SuffixTitles { get; set; }
        public string MaritalStatusCd { get; set; }
        public string MaritalStatusDesc { get; set; }
        public int? DeathFlag { get; set; }
        public DateOnly? DeathDate { get; set; }
        public string GDPRConsent { get; set; }
        public string MarketingConsent { get; set; }
        public int? NumberOfChildren { get; set; }
        public string USIndicator { get; set; }
        public string GATCAIndicator { get; set; }
        public string BirthNumber { get; set; }
        public string CountryOfBirth { get; set; }
        public int? PEP { get; set; }
        public string SourceSystem { get; set; }
    }
}